// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetResponse struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type BatchSetRequest struct {
	SetRequests          []*SetRequest `protobuf:"bytes,1,rep,name=setRequests,proto3" json:"setRequests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BatchSetRequest) Reset()         { *m = BatchSetRequest{} }
func (m *BatchSetRequest) String() string { return proto.CompactTextString(m) }
func (*BatchSetRequest) ProtoMessage()    {}
func (*BatchSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *BatchSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSetRequest.Unmarshal(m, b)
}
func (m *BatchSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSetRequest.Marshal(b, m, deterministic)
}
func (m *BatchSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSetRequest.Merge(m, src)
}
func (m *BatchSetRequest) XXX_Size() int {
	return xxx_messageInfo_BatchSetRequest.Size(m)
}
func (m *BatchSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSetRequest proto.InternalMessageInfo

func (m *BatchSetRequest) GetSetRequests() []*SetRequest {
	if m != nil {
		return m.SetRequests
	}
	return nil
}

type GetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MembershipProof struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	At                   uint64   `protobuf:"varint,4,opt,name=at,proto3" json:"at,omitempty"`
	Path                 [][]byte `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MembershipProof) Reset()         { *m = MembershipProof{} }
func (m *MembershipProof) String() string { return proto.CompactTextString(m) }
func (*MembershipProof) ProtoMessage()    {}
func (*MembershipProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *MembershipProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipProof.Unmarshal(m, b)
}
func (m *MembershipProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipProof.Marshal(b, m, deterministic)
}
func (m *MembershipProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipProof.Merge(m, src)
}
func (m *MembershipProof) XXX_Size() int {
	return xxx_messageInfo_MembershipProof.Size(m)
}
func (m *MembershipProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipProof.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipProof proto.InternalMessageInfo

func (m *MembershipProof) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MembershipProof) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MembershipProof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MembershipProof) GetAt() uint64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *MembershipProof) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

type MembershipRequest struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MembershipRequest) Reset()         { *m = MembershipRequest{} }
func (m *MembershipRequest) String() string { return proto.CompactTextString(m) }
func (*MembershipRequest) ProtoMessage()    {}
func (*MembershipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *MembershipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipRequest.Unmarshal(m, b)
}
func (m *MembershipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipRequest.Marshal(b, m, deterministic)
}
func (m *MembershipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipRequest.Merge(m, src)
}
func (m *MembershipRequest) XXX_Size() int {
	return xxx_messageInfo_MembershipRequest.Size(m)
}
func (m *MembershipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipRequest proto.InternalMessageInfo

func (m *MembershipRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type HealthResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*SetRequest)(nil), "schema.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "schema.SetResponse")
	proto.RegisterType((*BatchSetRequest)(nil), "schema.BatchSetRequest")
	proto.RegisterType((*GetRequest)(nil), "schema.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "schema.GetResponse")
	proto.RegisterType((*MembershipProof)(nil), "schema.MembershipProof")
	proto.RegisterType((*MembershipRequest)(nil), "schema.MembershipRequest")
	proto.RegisterType((*HealthResponse)(nil), "schema.HealthResponse")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x6f, 0xa2, 0x40,
	0x10, 0xc7, 0x23, 0x28, 0x31, 0x83, 0xd1, 0xbb, 0xbd, 0x8b, 0x72, 0x5c, 0x72, 0x31, 0xdc, 0x8b,
	0xf7, 0x82, 0x89, 0xe7, 0x83, 0x7d, 0x6b, 0x9a, 0x34, 0xb4, 0x0f, 0x4d, 0x1a, 0xf8, 0x04, 0xab,
	0x1d, 0xc5, 0x54, 0x5c, 0xca, 0x2e, 0xa6, 0x7e, 0x9e, 0x7e, 0xd1, 0x66, 0x77, 0x41, 0xb1, 0x62,
	0xfb, 0x36, 0x33, 0xfc, 0xfe, 0xec, 0xcc, 0x7f, 0x06, 0x3a, 0x7c, 0x11, 0x63, 0x42, 0xfd, 0x34,
	0x63, 0x82, 0x11, 0x4b, 0x67, 0xee, 0xef, 0x15, 0x63, 0xab, 0x0d, 0x8e, 0x55, 0x75, 0x9e, 0x2f,
	0xc7, 0x98, 0xa4, 0x62, 0xaf, 0x21, 0x6f, 0x0a, 0x10, 0xa1, 0x08, 0xf1, 0x25, 0x47, 0x2e, 0xc8,
	0x37, 0x30, 0x9f, 0x71, 0xef, 0x34, 0x86, 0x8d, 0x51, 0x27, 0x94, 0x21, 0xf9, 0x09, 0xad, 0x1d,
	0xdd, 0xe4, 0xe8, 0x18, 0xaa, 0xa6, 0x13, 0xef, 0x2f, 0xd8, 0x4a, 0xc5, 0x53, 0xb6, 0xe5, 0x28,
	0xa1, 0xf5, 0xf6, 0x09, 0x5f, 0x95, 0xb0, 0x19, 0xea, 0xc4, 0x0b, 0xa0, 0x77, 0x43, 0xc5, 0x22,
	0xae, 0xfc, 0x7f, 0x0a, 0x36, 0x3f, 0x64, 0xdc, 0x69, 0x0c, 0xcd, 0x91, 0x3d, 0x21, 0x7e, 0xd1,
	0xf6, 0x11, 0x0c, 0xab, 0x98, 0xf7, 0x07, 0x20, 0xf8, 0xa4, 0x47, 0xef, 0x0a, 0xec, 0xe0, 0xab,
	0x6e, 0x2e, 0x0c, 0xc2, 0xa1, 0xf7, 0x80, 0xc9, 0x1c, 0x33, 0x1e, 0xaf, 0xd3, 0xc7, 0x8c, 0xb1,
	0xe5, 0x05, 0x39, 0x81, 0x66, 0x4c, 0x79, 0x5c, 0xa8, 0x55, 0x2c, 0x6b, 0x19, 0x63, 0xc2, 0x31,
	0x75, 0x4d, 0xc6, 0xa4, 0x0b, 0x06, 0x15, 0x4e, 0x53, 0x49, 0x0d, 0x2a, 0x24, 0x93, 0x52, 0x11,
	0x3b, 0xad, 0xa1, 0x29, 0x19, 0x19, 0x7b, 0xff, 0xe0, 0xfb, 0xf1, 0xd1, 0x72, 0xac, 0x7a, 0x0f,
	0x47, 0xd0, 0xbd, 0x43, 0xba, 0x11, 0xf1, 0x61, 0xba, 0x3e, 0x58, 0x5c, 0x50, 0x91, 0x73, 0x05,
	0xb6, 0xc3, 0x22, 0x9b, 0xbc, 0x19, 0x60, 0xdf, 0x27, 0x49, 0x1e, 0x61, 0xb6, 0x5b, 0x2f, 0x90,
	0xf8, 0x60, 0x46, 0x28, 0x48, 0x8d, 0xb9, 0xee, 0x8f, 0x93, 0x5a, 0xf1, 0xdf, 0x19, 0xb4, 0x23,
	0x14, 0x6a, 0x61, 0x64, 0x50, 0x02, 0x1f, 0xf6, 0x57, 0xaf, 0xf4, 0xc1, 0x0c, 0xaa, 0x2f, 0x05,
	0x35, 0x7c, 0x75, 0x3f, 0xd7, 0x00, 0xc7, 0xf1, 0xc9, 0xaf, 0x12, 0x39, 0xb3, 0xc4, 0x1d, 0x9c,
	0x7f, 0xd2, 0x2b, 0x9a, 0x81, 0xa5, 0x5d, 0x21, 0x7d, 0x5f, 0x1f, 0xb7, 0x5f, 0x1e, 0xb7, 0x7f,
	0x2b, 0x8f, 0xdb, 0xed, 0x97, 0xd2, 0x53, 0xf7, 0xe6, 0x96, 0xe2, 0xfe, 0xbf, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x22, 0x4c, 0x09, 0xcd, 0x2a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImmuServiceClient is the client API for ImmuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImmuServiceClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	SetBatch(ctx context.Context, in *BatchSetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Membership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*MembershipProof, error)
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type immuServiceClient struct {
	cc *grpc.ClientConn
}

func NewImmuServiceClient(cc *grpc.ClientConn) ImmuServiceClient {
	return &immuServiceClient{cc}
}

func (c *immuServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/schema.ImmuService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) SetBatch(ctx context.Context, in *BatchSetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/schema.ImmuService/SetBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/schema.ImmuService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Membership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*MembershipProof, error) {
	out := new(MembershipProof)
	err := c.cc.Invoke(ctx, "/schema.ImmuService/Membership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/schema.ImmuService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImmuServiceServer is the server API for ImmuService service.
type ImmuServiceServer interface {
	Set(context.Context, *SetRequest) (*SetResponse, error)
	SetBatch(context.Context, *BatchSetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Membership(context.Context, *MembershipRequest) (*MembershipProof, error)
	Health(context.Context, *empty.Empty) (*HealthResponse, error)
}

// UnimplementedImmuServiceServer can be embedded to have forward compatible implementations.
type UnimplementedImmuServiceServer struct {
}

func (*UnimplementedImmuServiceServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedImmuServiceServer) SetBatch(ctx context.Context, req *BatchSetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBatch not implemented")
}
func (*UnimplementedImmuServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedImmuServiceServer) Membership(ctx context.Context, req *MembershipRequest) (*MembershipProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Membership not implemented")
}
func (*UnimplementedImmuServiceServer) Health(ctx context.Context, req *empty.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func RegisterImmuServiceServer(s *grpc.Server, srv ImmuServiceServer) {
	s.RegisterService(&_ImmuService_serviceDesc, srv)
}

func _ImmuService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ImmuService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_SetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).SetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ImmuService/SetBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).SetBatch(ctx, req.(*BatchSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ImmuService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Membership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Membership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ImmuService/Membership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Membership(ctx, req.(*MembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ImmuService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImmuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.ImmuService",
	HandlerType: (*ImmuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _ImmuService_Set_Handler,
		},
		{
			MethodName: "SetBatch",
			Handler:    _ImmuService_SetBatch_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ImmuService_Get_Handler,
		},
		{
			MethodName: "Membership",
			Handler:    _ImmuService_Membership_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ImmuService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
